version: "3.9"

services:
  # --------------------------- #
  #        REDIS SERVICE        #
  # --------------------------- #
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - fraud-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Redis Exporter for Prometheus
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      REDIS_ADDR: "redis:6379"
    ports:
      - "9121:9121"
    networks:
      - fraud-net
    depends_on:
      - redis

  # --------------------------- #
  #        MONGODB SERVICE      #
  # --------------------------- #
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - fraud-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  # MongoDB Exporter for Prometheus
  mongo-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo_exporter
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    ports:
      - "9216:9216"
    networks:
      - fraud-net
    depends_on:
      - mongo

  # --------------------------- #
  #          MLFLOW             #
  # --------------------------- #
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    networks:
      - fraud-net
    command: >
      mlflow server
        --backend-store-uri sqlite:////mlflow/mlflow.db
        --default-artifact-root /mlflow/artifacts
        --host 0.0.0.0
        --port 5000

  # --------------------------- #
  #         PROMETHEUS          #
  # --------------------------- #
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fraud-net
    depends_on:
      - redis-exporter
      - mongo-exporter

  # --------------------------- #
  #          GRAFANA            #
  # --------------------------- #
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    networks:
      - fraud-net
    depends_on:
      - prometheus

# --------------------------- #
#         NETWORK SETUP       #
# --------------------------- #
networks:
  fraud-net:
    driver: bridge
