services:
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: airflow
      MONGO_INITDB_ROOT_PASSWORD: airflow12345
      MONGO_INITDB_DATABASE: airflow
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow-webserver:
    image: apache/airflow:2.10.1
    depends_on:
      - mongodb
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mongodb+srv://airflow:airflow12345@mongodb:27017/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.1
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mongodb+srv://airflow:airflow12345@mongodb:27017/$airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: $minio
      MINIO_ROOT_PASSWORD: $minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


volumes:
  mongo_data:
  minio_data:
